---
- name: Disable SELinux
  hosts: all
  connection: ssh

  gather_facts: yes
  tasks:
    - name: Get IP address
      debug: var=hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive
    
    - name: Create a file in /etc/ to note the change
      ansible.builtin.file:
        path: /etc/changed
        state: touch
        mode: '0644'