---
- name: Find some details about an IBM i system
  hosts: ibmi
  collections:
    - ibm.power_ibmi
    
  tasks:
  - name: collect IBM i information
    ibm.power_ibmi.ibmi_facts:
    register: facts_result

  - name: show system information
    ansible.builtin.debug:
      var: facts_result.ansible_facts.system_info

  - name: show system name
    ansible.builtin.debug:
      var: facts_result.ansible_facts.system_name